-- Generated by HyprMod
hl.config({
    decoration = {
        dim_inactive = 1,
        inactive_opacity = 1.0,
        rounding = 2,
    },
    general = {
        border_size = 2,
        gaps_in = 1,
        gaps_out = 2,
    },
})
